const brandsData = [
    {
        name: "airjordan",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/airjordan.jpg",
    },
    {
        name: "nike",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/nike.png",
    },
    {
        name: "puma",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/pumablack.png",
    },
    {
        name: "airjordan",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/airjordan.jpg",
    },
    {
        name: "puma",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/pumablack.png",
    },
    {
        name: "adidas",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/adidas3.jpg",
    },
    {
        name: "airjordan",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/airjordan.jpg",
    },
    {
        name: "nike",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/nike.png",
    },
    {
        name: "puma",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/pumablack.png",
    },
    {
        name: "adidas",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/adidas3.jpg",
    },
    {
        name: "airjordan",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/airjordan.jpg",
    },
    {
        name: "nike",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/nike.png",
    },
    {
        name: "puma",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/pumablack.png",
    },
    {
        name: "adidas",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/adidas3.jpg",
    },
    {
        name: "airjordan",
        products: 250,
        rating: 4.6,
        reviews: 150,
        categories: ["Clothing", "Shoes"],
        image: "/airjordan.jpg",
    },
];

export async function GET() {
    return Response.json({ result: brandsData });
}